"use client"

import { formatCurrency, formatDate } from "@/lib/utils"

interface ReceiptDocumentProps {
  receiptNumber: string
  dateReceived: string
  payerName: string
  amount: number
  rentPeriodStart?: string
  rentPeriodEnd?: string
  propertyAddress: string
  arrearsAtPayment: number
  paymentMethod: string
  bankReference?: string
}

export function ReceiptDocument({
  receiptNumber,
  dateReceived,
  payerName,
  amount,
  rentPeriodStart,
  rentPeriodEnd,
  propertyAddress,
  arrearsAtPayment,
  paymentMethod,
  bankReference,
}: ReceiptDocumentProps) {
  return (
    <div className="max-w-2xl mx-auto bg-white p-8 print:p-0">
      {/* Header */}
      <div className="border-b-2 border-primary pb-6 mb-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-primary">Renlio</h1>
            <p className="text-sm text-muted-foreground">Property Management System</p>
          </div>
          <div className="text-right">
            <div className="inline-block bg-primary text-white px-4 py-2 rounded-lg">
              <span className="text-sm font-medium">RENT RECEIPT</span>
            </div>
            <p className="text-sm text-muted-foreground mt-2">Receipt #: {receiptNumber}</p>
          </div>
        </div>
      </div>

      {/* Property Section */}
      <div className="mb-8">
        <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-2">Property</h2>
        <p className="text-lg font-medium text-foreground">{propertyAddress}</p>
      </div>

      {/* Payment Details */}
      <div className="grid grid-cols-2 gap-6 mb-8">
        <div>
          <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-2">Date Received</h2>
          <p className="text-lg font-medium text-foreground">{formatDate(dateReceived)}</p>
        </div>
        <div>
          <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-2">Payer Name</h2>
          <p className="text-lg font-medium text-foreground">{payerName}</p>
        </div>
        <div>
          <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-2">Amount Paid</h2>
          <p className="text-2xl font-bold text-primary">{formatCurrency(amount)}</p>
        </div>
        <div>
          <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-2">Payment Method</h2>
          <p className="text-lg font-medium text-foreground capitalize">{paymentMethod.toLowerCase().replace(/_/g, " ")}</p>
        </div>
      </div>

      {/* Bank Reference */}
      {bankReference && (
        <div className="mb-8">
          <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-2">Bank Reference</h2>
          <p className="text-lg font-medium text-foreground">{bankReference}</p>
        </div>
      )}

      {/* Period Covered */}
      {rentPeriodStart && rentPeriodEnd && (
        <div className="mb-8 p-4 bg-surface rounded-lg">
          <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wide mb-2">Period Covered</h2>
          <p className="text-lg font-medium text-foreground">
            {formatDate(rentPeriodStart)} — {formatDate(rentPeriodEnd)}
          </p>
        </div>
      )}

      {/* Arrears Section */}
      <div className="mb-8 p-4 rounded-lg border-2 ${arrearsAtPayment > 0 ? 'border-destructive bg-red-50' : 'border-success bg-green-50'}">
        <h2 className="text-sm font-medium uppercase tracking-wide mb-2">Arrears at Time of Payment</h2>
        {arrearsAtPayment > 0 ? (
          <div className="text-destructive">
            <p className="text-2xl font-bold">{formatCurrency(arrearsAtPayment)}</p>
            <p className="text-sm">Outstanding balance after this payment</p>
          </div>
        ) : (
          <div className="text-success">
            <p className="text-2xl font-bold">CLEAR</p>
            <p className="text-sm">No outstanding arrears</p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="border-t border-border pt-6 mt-8 text-center">
        <p className="text-sm text-muted-foreground">
          This is an official rent receipt generated by Renlio
        </p>
        <p className="text-xs text-muted-foreground mt-1">
          Receipt generated on {formatDate(new Date().toISOString())}
        </p>
      </div>
    </div>
  )
}
